// Build-time extraction of the Pembrokeshire coastline from Natural Earth 1:10m
// land polygons (via the world-atlas package). Output is a static TS module so
// the site ships no mapping library and no runtime data fetch.
import { writeFileSync, readFileSync, mkdirSync } from "node:fs";
import { feature } from "topojson-client";

const topo = JSON.parse(readFileSync("node_modules/world-atlas/land-10m.json", "utf8"));
const land = feature(topo, topo.objects.land);

const BOX = { w: -5.45, e: -4.45, s: 51.55, n: 52.15 };
const inBox = ([x, y]) => x >= BOX.w && x <= BOX.e && y >= BOX.s && y <= BOX.n;

const midLat = (BOX.n + BOX.s) / 2;
const k = Math.cos((midLat * Math.PI) / 180);
const W = 1000;
const s = W / ((BOX.e - BOX.w) * k);
const H = Math.round((BOX.n - BOX.s) * s);
const px = ([lon, lat]) => [+((lon - BOX.w) * k * s).toFixed(1), +((BOX.n - lat) * s).toFixed(1)];

const runs = [];
for (const f of land.features) {
  const polys = f.geometry.type === "Polygon" ? [f.geometry.coordinates] : f.geometry.coordinates;
  for (const poly of polys) for (const ring of poly) {
    let run = [];
    const flush = () => { if (run.length > 2) runs.push(run); run = []; };
    for (let i = 0; i < ring.length; i++) {
      if (inBox(ring[i])) { if (!run.length && i > 0) run.push(ring[i - 1]); run.push(ring[i]); }
      else { if (run.length) run.push(ring[i]); flush(); }
    }
    flush();
  }
}
runs.sort((a, b) => b.length - a.length);
const toPath = (r) => "M" + r.map(px).map((q) => q.join(",")).join("L");
const coast = runs.map(toPath).join("");
const landFill = toPath(runs[0]) + "Z";

const TOWNS = [
  ["St Davids", -5.269, 51.882], ["Fishguard", -4.977, 51.996], ["Newport", -4.833, 52.018],
  ["Haverfordwest", -4.969, 51.801], ["Narberth", -4.744, 51.798], ["Milford Haven", -5.043, 51.714],
  ["Pembroke", -4.917, 51.674], ["Saundersfoot", -4.692, 51.711], ["Tenby", -4.703, 51.673],
];
const towns = TOWNS.map(([name, lon, lat]) => { const [x, y] = px([lon, lat]); return { name, x, y }; });

/* A signed distance field of the coastline, baked to a small 8-bit grid. The
   terrain shader samples this in its vertex stage to morph a procedural
   landscape into the real shape of the county. 128 is plenty: the geometry it
   drives is smooth, and it keeps the payload around 20kB of base64. */
const SDF = 128;
const ring = runs[0].map(px);
const inside = (x, y) => {
  let hit = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i];
    const [xj, yj] = ring[j];
    if (yi > y !== yj > y && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) hit = !hit;
  }
  return hit;
};
const segDist = (x, y) => {
  let best = Infinity;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i];
    const [xj, yj] = ring[j];
    const dx = xj - xi, dy = yj - yi;
    const t = Math.max(0, Math.min(1, ((x - xi) * dx + (y - yi) * dy) / (dx * dx + dy * dy || 1)));
    const px2 = xi + t * dx - x, py2 = yi + t * dy - y;
    const d = px2 * px2 + py2 * py2;
    if (d < best) best = d;
  }
  return Math.sqrt(best);
};

/* Sampled over the map frame, not the raw bbox, so the shape sits centred. */
const FRAME = { x: 132, y: -14, w: 836, h: 928 };
const REACH = 260; // distance in projected units that saturates the field
const field = new Uint8Array(SDF * SDF);
for (let j = 0; j < SDF; j++) {
  for (let i = 0; i < SDF; i++) {
    const x = FRAME.x + ((i + 0.5) / SDF) * FRAME.w;
    const y = FRAME.y + ((j + 0.5) / SDF) * FRAME.h;
    const d = Math.min(segDist(x, y), REACH) / REACH;
    const signed = inside(x, y) ? d : -d;
    field[j * SDF + i] = Math.round((signed * 0.5 + 0.5) * 255);
  }
}

mkdirSync("src/data", { recursive: true });
writeFileSync("src/data/pembrokeshire.ts",
`// Generated by map.mjs. Coastline: Natural Earth 1:10m land polygons (public domain),
// clipped to Pembrokeshire and projected equirectangular at the county's mid latitude.
// Regenerate with: node map.mjs
export const MAP_W = ${W};
export const MAP_H = ${H};
export const COAST_PATH = "${coast}";
export const LAND_PATH = "${landFill}";
export type Town = { name: string; x: number; y: number };
export const TOWNS: Town[] = ${JSON.stringify(towns)};

/* Signed distance to the shoreline on a ${SDF}x${SDF} grid, row major, 8 bit.
   128 is the waterline, above it is land, below it is sea. */
export const COAST_SDF_SIZE = ${SDF};
export const COAST_SDF = "${Buffer.from(field).toString("base64")}";
`);
console.log("viewBox", W, H, "| coast chars", coast.length, "| towns", towns.length, "| sdf", SDF, "x", SDF);
